### ISSUE TITLE
Can I prevent this scan?

### ISSUE THREAD

**Issue by dnsconfused** [mandatoryprogrammer/TLDR#4]
Other such "DNS scanning" services provide an opt-out.
Does this have such a "feature"

To be honest, other than "mildly interesting" what good is this continual scan and zone transfer request of every NS?  Please contact me for more info on why I wish this would stop.

**Comment by mandatoryprogrammer** [comment]
Unless you are a TLD DNS provider you won't have a zone transfer attempted against your nameserver. 

Do you currently run a TLD nameserver? If so you can trivially disable global zone transfers to prevent this.

**Comment by mandatoryprogrammer** [comment]
Don't have an easy way to contact you but interested in hearing your use case, you can always email me at mandatory ( at ) gmail.com.

**Comment by JonathanMerritt** [comment]
Was brought here by a trend list... 

Sorry to post @mandatoryprogrammer, but I want the sub because this has me very curious.

It seems like @dnsconfused created a GitHub account for the sole purpose of finding ways around this simple log...

**Comment by staff0rd** [comment]
Same reason I subbed, 'cept I came from the DPRK leak.

**Comment by mandatoryprogrammer** [comment]
Thanks for the input guys, I actually got an email from this person and will be following up there. I don't plan on adding exceptions to this project for a number of reasons, one of them being that it's just a false sense of security since other people will collect it anyways. Closing this thread since I'll follow up with the email.

**Comment by dnsconfused** [comment]
No follow up received.
